### ISSUE TITLE
Generate minified versions

### ISSUE THREAD

**Issue by papjul** [Norviah/animal-crossing#9]
Would it be possible to provide minified versions of combined files (in addition to existing ones in case some people want readable files)? Such as Items.min.json.

I believe there are many libraries that can do it, or a manual tab/space/linebreak remover is probably fine too.

**Comment by Norviah** [comment]
i see what ya mean, ill look into it and see what i can do

**Comment by Norviah** [comment]
alright, i just pushed a change that implements minified versions. `src/combined` contains the json file and the minified version, similar to what you suggested. `bin/minify.sh` generates the minified version and then saves the minified version to the module, then the program does what it needs to do etc.

**Comment by Norviah** [comment]
ill leave the issue open for a bit to see if ya have any more ideas or suggestions regarding minifying the files
